#!/usr/bin/python

import ram.context
import ram.widgets


with ram.context(__name__):
    from wiz.entry import UnitEntry

if __name__ == '__main__':
    ram.widgets.RunMenu(
        "Select action",
        [
            ("Interface configuration ...", UnitEntry('net.ifconfig', apply=False)),
            ("", 0),
            ("Routing configuration ...", UnitEntry('net.routing', apply=False)),
            ("Change the system hostname ...", UnitEntry('net.hostname', apply=False)),
            ("DNS resolver configuration ...", UnitEntry('net.resolver', apply=False)),
        ]
    )
