#!/usr/bin/python

import ram.context
import ram.symbols

from ram.osutils import TrySubmit

with ram.context(__name__):
    from net.ifcfg import QueryNetworkConfiguration
    from net.ifcfg import StoreNetworkConfiguration
    from net.aliases import update_localhost_alias

if __name__ == '__main__':
    netcfg = QueryNetworkConfiguration()
    config = ram.symbols.recv()

    netcfg.SetHostname(config['hostname'])

    StoreNetworkConfiguration(netcfg)

    # update /etc/hosts
    update_localhost_alias(config['hostname'])

    if not TrySubmit('/etc/hostname', [config['hostname']]):
        raise IOError("Failed to update `/etc/hostname`.")
