#!/usr/bin/python


import ram.unitlib
import ram.widgets


config = ram.unitlib.Config()


class Entry(object):
    def __init__(self, config):
        self.config = config

    def __str__(self):
        return config[self.config]
        # return query(self.config)

    def __iter__(self):
        yield "Data", query(self.config), arguments_to_call
        yield "....", "", arguments_to_call

    def __call__(self):
        # handle modify switch logic

        data = ram.widgets.RunEntry(
            "Enter data",
            "",
            [
                ("Data", config[self.config], lambda x: x)
            ]
        )

        config[self.config], = data

        # check(self.config)
        # store(self.config)


if __name__ == '__main__':
    entry = Entry('data')

    def _mkmenu():
        return [
            ("Data: %s" % str(entry), entry),
        ]

    ram.widgets.RunMenu(
        "Select action",
        _mkmenu,
    )
