#!/usr/bin/python

import ram.symbols


if __name__ == '__main__':
    config = ram.query('net.network')

    ifaces = [
        ifname for ifname in config['ifconfig'].keys()
        if config['ifconfig'][ifname]['enabled']
        and config['ifconfig'][ifname]['usedhcp']
    ]

    config['resolver']['ifaces'] = " ".join(sorted(ifaces))

    ram.symbols.send(config['resolver'])
