#!/usr/bin/python

import ram.process
import ram.symbols

from datetime import datetime


if __name__ == '__main__':
    config = ram.symbols.recv()

    dt = datetime.fromtimestamp(float(config['timestamp']))
    ram.process.output('date -s "%s"' % str(dt))
