#!/usr/bin/python

import libuser

import ram.symbols


if __name__ == '__main__':
    config = ram.symbols.recv()

    admin = libuser.admin()

    user = admin.lookupUserByName(config['username'])
    if not user:
        user = admin.initUser(config['username'])
        admin.addUser(user)

    group = admin.lookupGroupByName(config['username'])
    if not group:
        group = admin.initGroup(config['username'])
        admin.addGroup(group)

    user[libuser.GECOS] = "#"
    user[libuser.GIDNUMBER] = group[libuser.GIDNUMBER]
    user[libuser.LOGINSHELL] = config['useshell']

    for groupname in config['ingroups'].split():
        if groupname:
            group = admin.lookupGroupByName(groupname)
            if not group:
                group = admin.initGroup(groupname)
                admin.addGroup(group)
            group.add(libuser.MEMBERNAME, config['username'])
            admin.modifyGroup(group)

    admin.modifyUser(user)

    admin.setpassUser(user, config['password'], is_crypted=True)
